export const USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS';
export const USER_SEARCH_REQUEST = 'USER_SEARCH_REQUEST';
export const USER_SEARCH_FAIL = 'USER_SEARCH_FAIL';

export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_REQUEST = 'USER_GET_REQUEST';
export const USER_GET_FAIL = 'USER_GET_FAIL';

export const USER_GET_REPOS_SUCCESS = 'USER_GET_REPOS_SUCCESS';
export const USER_GET_REPOS_REQUEST = 'USER_GET_REPOS_REQUEST';
export const USER_GET_REPOS_FAIL = 'USER_GET_REPOS_FAIL';

export const USER_GET_GISTS_SUCCESS = 'USER_GET_GISTS_SUCCESS';
export const USER_GET_GISTS_REQUEST = 'USER_GET_GISTS_REQUEST';
export const USER_GET_GISTS_FAIL = 'USER_GET_GISTS_FAIL';

export const USER_GET_STARRED_SUCCESS = 'USER_GET_STARRED_SUCCESS';
export const USER_GET_STARRED_REQUEST = 'USER_GET_STARRED_REQUEST';
export const USER_GET_STARRED_FAIL = 'USER_GET_STARRED_FAIL';