export const USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS';
export const USER_SEARCH_REQUEST = 'USER_SEARCH_REQUEST';
export const USER_SEARCH_FAIL = 'USER_SEARCH_FAIL';

export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_REQUEST = 'USER_GET_REQUEST';
export const USER_GET_FAIL = 'USER_GET_FAIL';